# This line ensures Cloudflare Pages uses this wrangler.toml for Functions settings
pages_build_output_dir = "./public" # Or your actual static build output directory (e.g., ./dist, ./build)

# It's good practice to have a name for your Pages project functions environment
name = "my-pages-project-functions" # Can be anything descriptive

# CRUCIAL: Set a recent compatibility date
compatibility_date = "2024-05-01" # Use a recent date (check Cloudflare docs for the latest recommended)

# CRUCIAL: Enable Node.js compatibility flags
compatibility_flags = [ "nodejs_compat" ]